const investments = [
    {
        name: "Af U.S Government Money Market-R2",
        docs: "",
        assetClass: "Capital Preservation",
        currentBalance: 41035.30,
        currentUnits: 41035.300,
        amountToExchange: 0,
    },
    {
        name: "Af Global Insight Fund-R2",
        docs: "",
        assetClass: "Growth",
        currentBalance: 4788.15,
        currentUnits: 176.75,
        amountToExchange: 0,
    },
    {
        name: "Af International Vantage Fund-R2",
        docs: "",
        assetClass: "Growth",
        currentBalance: 0,
        currentUnits: 0,
        amountToExchange: 0,
    },
    {
        name: "Af Moderate Growth And Income-R2",
        docs: "",
        assetClass: "Balanced",
        currentBalance: 0,
        currentUnits: 0,
        amountToExchange: 0,
    },
    {
        name: "American Funds 2010 Target Date-R2",
        docs: "",
        assetClass: "Target Date",
        currentBalance: 0,
        currentUnits: 0,
        amountToExchange: 0,
    },
    {
        name: "American Funds 2015 Target Date-R2",
        docs: "",
        assetClass: "Target Date",
        currentBalance: 0,
        currentUnits: 0,
        amountToExchange: 0,
    },
    {
        name: "American Funds 2020 Target Date-R2",
        docs: "",
        assetClass: "Target Date",
        currentBalance: 0,
        currentUnits: 0,
        amountToExchange: 0,
    },
    {
        name: "American Funds 2025 Target Date-R2",
        docs: "",
        assetClass: "Target Date",
        currentBalance: 0,
        currentUnits: 0,
        amountToExchange: 0,
    },
    {
        name: "American Funds 2030 Target Date-R2",
        docs: "",
        assetClass: "Target Date",
        currentBalance: 0,
        currentUnits: 0,
        amountToExchange: 0,
    },  
    {
        name: "American Funds 2035 Target Date-R2",
        docs: "",
        assetClass: "Target Date",
        currentBalance: 0,
        currentUnits: 0,
        amountToExchange: 0,
    },
    {
        name: "American Funds 2040 Target Date-R2",
        docs: "",
        assetClass: "Target Date",
        currentBalance: 0,
        currentUnits: 0,
        amountToExchange: 0,
    },      
    {
        name: "American Funds 2045 Target Date-R2",
        docs: "",
        assetClass: "Target Date",
        currentBalance: 0,
        currentUnits: 0,
        amountToExchange: 0,
    },
    {
        name: "American Funds 2050 Target Date-R2",
        docs: "",
        assetClass: "Target Date",
        currentBalance: 0,
        currentUnits: 0,
        amountToExchange: 0,
    },
    {
        name: "American Funds 2055 Target Date-R2",
        docs: "",
        assetClass: "Target Date",
        currentBalance: 0,
        currentUnits: 0,
        amountToExchange: 0,
    },
    {
        name: "American Funds 2060 Target Date-R2",
        docs: "",
        assetClass: "Target Date",
        currentBalance: 0,
        currentUnits: 0,
        amountToExchange: 0,
    },
    {
        name: "American Funds 2065 Target Date-R2",
        docs: "",
        assetClass: "Target Date",
        currentBalance: 0,
        currentUnits: 0,
        amountToExchange: 0,
    },  
    {
        name: "American Funds 2070 Target Date-R2",
        docs: "",
        assetClass: "Target Date",
        currentBalance: 0,
        currentUnits: 0,
        amountToExchange: 0,
    },
    {
        name: "American High-Income Trust-R2",
        docs: "",
        assetClass: "Bond",
        currentBalance: 0,
        currentUnits: 0,
        amountToExchange: 0,
    },
    {
        name: "Capital Income Builder-R2",
        docs: "",
        assetClass: "Equity Income",
        currentBalance: 0,
        currentUnits: 0,
        amountToExchange: 0,
    },
    {
        name: "Capital World Growth And Income-R2",
        docs: "",
        assetClass: "Growth-And-Income",
        currentBalance: 0,
        currentUnits: 0,
        amountToExchange: 0,
    },
    {
        name: "Corporate Bond Fund-A",
        docs: "",
        assetClass: "Bond",
        currentBalance: 0,
        currentUnits: 0,
        amountToExchange: 0,
    },
    {
        name: "Corporate Bond Fund-R2",
        docs: "",
        assetClass: "Bond",
        currentBalance: 0,
        currentUnits: 0,
        amountToExchange: 0,
    },
    {
        name: "Corporate Bond Fund-R4",
        docs: "",
        assetClass: "Bond",
        currentBalance: 0,
        currentUnits: 0,    
        amountToExchange: 0,
    },
    {
        name: "Corporate Bond Fund-R5",
        docs: "",
        assetClass: "Bond",
        currentBalance: 0,
        currentUnits: 0,
        amountToExchange: 0,
    },
    {
        name: "Emerging Markets Bond Fund-A",
        docs: "",
        assetClass: "Bond",
        currentBalance: 0,
        currentUnits: 0,
        amountToExchange: 0,
    },
    {
        name: "Emerging Markets Bond Fund-R2",
        docs: "",
        assetClass: "Bond",
        currentBalance: 0,
        currentUnits: 0,
        amountToExchange: 0,
    },
    {
        name: "Emerging Markets Bond Fund-R4",
        docs: "",
        assetClass: "Bond",
        currentBalance: 0,
        currentUnits: 0,
        amountToExchange: 0,
    },
    {
        name: "Emerging Markets Bond Fund-R5",
        docs: "",
        assetClass: "Bond",
        currentBalance: 0,
        currentUnits: 0,
        amountToExchange: 0,
    },
    {
        name: "Eupac Fund-R2",
        docs: "",
        assetClass: "Growth",
        currentBalance: 0,
        currentUnits: 0,
        amountToExchange: 0,
    },
    {
        name: "Global Balanced Fund-R2",
        docs: "",
        assetClass: "Balanced",
        currentBalance: 0,
        currentUnits: 0,
        amountToExchange: 0,
    },
    {
        name: "Inflation Linked Bond Fund-R2",
        docs: "",
        assetClass: "Bond",
        currentBalance: 0,
        currentUnits: 0,
        amountToExchange: 0,
    },
    {
        name: "New Perspective Fund-R2",
        docs: "",
        assetClass: "Growth",
        currentBalance: 0,
        currentUnits: 0,
        amountToExchange: 0,
    },
    {
        name: "New World Fund-R2",
        docs: "",
        assetClass: "Growth",
        currentBalance: 0,
        currentUnits: 0,
        amountToExchange: 0,
    },
    {
        name: "Strategic Bond Fund-A",
        docs: "",
        assetClass: "Bond",
        currentBalance: 0,
        currentUnits: 0,
        amountToExchange: 0,
    },
    {
        name: "Strategic Bond Fund-R3",
        docs: "",
        assetClass: "Bond",
        currentBalance: 0,
        currentUnits: 0,
        amountToExchange: 0,
    },
    {
        name: "Strategic Bond Fund-R4",
        docs: "",
        assetClass: "Bond",
        currentBalance: 0,
        currentUnits: 0,
        amountToExchange: 0,
    },
    {
        name: "The Bond Fund Of America-R2",
        docs: "",
        assetClass: "Bond",
        currentBalance: 0,
        currentUnits: 0,
        amountToExchange: 0,
    },
    {
        name: "The Growth Fund Of America-R2",
        docs: "",
        assetClass: "Growth",
        currentBalance: 0,
        currentUnits: 0,
        amountToExchange: 0,
    },
    {
        name: "The Investment Company Of America-R2",
        docs: "",
        assetClass: "Growth-And-Income",
        currentBalance: 0,
        currentUnits: 0,
        amountToExchange: 0,
    },
    {
        name: "The New Economy Fund-R2",
        docs: "",
        assetClass: "Growth",
        currentBalance: 0,
        currentUnits: 0,
        amountToExchange: 0,
    },
    {
        name: "Washington Mutual Investmentors Fund-R2",
        docs: "",
        assetClass: "Growth-And-Income",
        currentBalance: 0,
        currentUnits: 0,
        amountToExchange: 0,
    },
];

export default investments;
