



export const termsAndConditions = `
1. Advanced Bank Verification - Banking Authorization Terms and Conditions:
\n
Electronic bank verification is conducted through a third party service provider that is unaffiliated with MetroHill. If you choose to add a bank account electronically, you must agree to the Bank Verification Terms & Conditions of Use set forth below. The Fund or the Fund's transfer agent will send your information to the third party service provider, who will then compare your information with their database to verify the information you provided. Please read and agree to the below Bank Verification Terms and Conditions of Use for the third party service in order to continue.
\n
\n
Agreement and Bank Verification Terms & Conditions of Use of the Service
\n
By acknowledging below, I (we) authorize the Fund and its agents to act upon instructions (by phone, in writing, online or by other means) believed to be genuine and in accordance with procedures described in the prospectus (if applicable) for this designated bank account. I (we) authorize credits/debits to/from the bank account designated in conjunction with the account option(s) selected. I (we) agree that MetroHill shall be fully protected in honoring any such transaction. I (we) also agree that MetroHill may make additional attempts to credit/debit my (our) account if the initial attempt fails and I (we) will be liable for any associated costs. All account options elected will become part of the account and terms, representations, and conditions thereof.
\n
Provide Accurate Information. I (we), the end user, agree to provide true, accurate, current and complete information about myself (ourselves) and my (our) accounts maintained at other web sites and I (we) agree to not misrepresent my (our) identity or my (our) account
\n
Proprietary Rights. I (we) are permitted to use content delivered to me (us) through the service only on the service. I (we) may not copy, reproduce, distribute, or create derivative works from this content. Further, I (we) agree not to reverse engineer or reverse compile any of the service technology, including but not limited to, any Java applets associated with the service.
\n
Content You Provide. I (we) are licensing to MetroHill ("Company") and its service providers ("Service Provider") any information, data, materials or other content (collectively, "Content") I (we) provide through or to the service. Company and Service Provider may use, modify, display, distribute and create new material using such Content to provide the service to you. By submitting Content, I (we) automatically agree, or promise that the owner of such Content has expressly agreed that, without any particular time limit, and without the payment of any fees, Company and Service Provider may use the Content for the purposes set out above. I (we) agree that, as between Company and Service Provider, Company owns your confidential account information.
\n
Third Party Accounts. By using the service, I (we) authorize Company and Service Provider to access third party sites designated by Company, on my (our) behalf, to retrieve information requested by me (us), and to register for accounts requested by me (us). For all purposes hereof, I (we) hereby grant Company and Service Provider a limited power of attorney, and I (we) hereby appoint Company and Service Provider as my (our) true and lawful attorney-in-fact and agent, with full power of substitution and re-substitution, for me (us) and in my (our) name, place and stead, in any and all capacities, to access third party internet sites, servers or documents, retrieve information, and use your information, all as described above, with the full power and authority to do and perform each and every act and thing requisite and necessary to be done in connection with such activities, as fully to all intents and purposes as you might or could do in person. I (WE) ACKNOWLEDGE AND AGREE THAT WHEN COMPANY OR SERVICE PROVIDER ACCESSES AND RETRIEVES INFORMATION FROM THIRD PARTY SITES, COMPANY AND SERVICE PROVIDER ARE ACTING AS MY (OUR) AGENT, AND NOT THE AGENT OR ON BEHALF OF THE THIRD PARTY. I (we) agree that third party account providers shall be entitled to rely on the foregoing authorization, agency and power of attorney granted by me (us). I (we) understand and agree that the service is not endorsed or sponsored by any third party account providers accessible through the service.
\n
DISCLAIMER OF WARRANTIES. I (WE) EXPRESSLY UNDERSTAND AND AGREE THAT: MY (OUR) USE OF THE SERVICE AND ALL INFORMATION, PRODUCTS AND OTHER CONTENT (INCLUDING THAT OF THIRD PARTIES) INCLUDED IN OR ACCESSIBLE FROM THE SERVICE IS AT MY (OUR) SOLE RISK. THE SERVICE IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS. COMPANY AND SERVICE PROVIDER EXPRESSLY DISCLAIM ALL WARRANTIES OF ANY KIND AS TO THE SERVICE AND ALL INFORMATION, PRODUCTS AND OTHER CONTENT (INCLUDING THAT OF THIRD PARTIES) INCLUDED IN OR ACCESSIBLE FROM THE SERVICE, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. COMPANY AND SERVICE PROVIDER MAKE NO WARRANTY THAT (i) THE SERVICE WILL MEET MY (OUR) REQUIREMENTS, (ii) THE SERVICE WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE, (iii) THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF THE SERVICE WILL BE ACCURATE OR RELIABLE, (iv) THE QUALITY OF ANY PRODUCTS, SERVICES, INFORMATION, OR OTHER MATERIAL PURCHASED OR OBTAINED BY ME (US) THROUGH THE SERVICE WILL MEET MY (OUR) EXPECTATIONS, OR (V) ANY ERRORS IN THE TECHNOLOGY WILL BE CORRECTED. ANY MATERIAL DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE USE OF THE SERVICE IS DONE AT MY (OUR) OWN DISCRETION AND RISK AND I (WE) ARE SOLELY RESPONSIBLE FOR ANY DAMAGE TO MY (OUR) COMPUTER SYSTEM OR LOSS OF DATA THAT RESULTS FROM THE DOWNLOAD OF ANY SUCH MATERIAL. NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY ME (US) FROM COMPANY OR SERVICE PROVIDER THROUGH OR FROM THE SERVICE WILL CREATE ANY WARRANTY NOT EXPRESSLY STATED IN THESE TERMS.
\n
LIMITATION OF LIABILITY. I (WE) AGREE THAT NEITHER COMPANY, ITS INVESTMENT MANAGER, OR SERVICE PROVIDER NOR ANY OF THEIR EMPLOYEES, OFFICERS, TRUSTEES, DIRECTORS, AFFILIATES, ACCOUNT PROVIDERS OR ANY OF THEIR AFFILIATES WILL BE LIABLE FOR ANY HARMS, WHICH LAWYERS AND COURTS OFTEN CALL DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR EXEMPLARY DAMAGES, INCLUDING, BUT NOT LIMITED TO, DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA OR OTHER INTANGIBLE LOSSES, EVEN IF COMPANY OR SERVICE PROVIDER HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, RESULTING FROM: (i) THE USE OR THE INABILITY TO USE THE SERVICE; (ii) THE COST OF GETTING SUBSTITUTE GOODS AND SERVICES, (iii) ANY PRODUCTS, DATA, INFORMATION OR SERVICES PURCHASED OR OBTAINED OR MESSAGES RECEIVED OR TRANSACTIONS ENTERED INTO, THROUGH OR FROM THE SERVICE;(iv) UNAUTHORIZED ACCESS TO OR ALTERATION OF YOUR TRANSMISSIONS OR DATA; (v) STATEMENTS OR CONDUCT OF ANYONE ON THE SERVICE; (vi) THE USE, INABILITY TO USE, UNAUTHORIZED USE, PERFORMANCE OR NON-PERFORMANCE OF ANY THIRD PARTY ACCOUNT PROVIDER SITE, EVEN IF THE PROVIDER HAS BEEN ADVISED PREVIOUSLY OF THE POSSIBILITY OF SUCH DAMAGES; OR (vii) ANY OTHER MATTER RELATING TO THE SERVICE.
\n
Indemnification. I (we) agree to protect and fully compensate Company, its investment manager, and Service Provider and their employees, officers, trustees, directors, and affiliates from any and all third party claims, liability, damages, expenses and costs (including, but not limited to, reasonable fees) caused by or arising from my (our) use of the service, my (our) violation of these terms or my (our) infringement, or infringement by any other user of my (our) account, of any intellectual property or other right of anyone. I (we) agree that the Company's investment manager and Service Provider are each a third party beneficiary of the above provisions, with all rights to enforce such provisions as if the investment manager or Service Provider were a party to this Agreement.`;